#' Trial Data
#'
#' This dataset is generated based on the first three enrollment windows outlined in Figure 1(a) in our paper.
#'
#' @format A data frame with 500 rows and 8 columns:
#'   \describe{
#'     \item{xc, xb, subtype}{The covariates.}
#'     \item{t, substudy}{The enrollment window and substudy assignment}
#'     \item{treatment}{The treatment assignment, "1", "2", "3" and "4"}
#'     \item{y}{The continuous response.}
#'     \item{y_b}{The binary response, I(y>3).}
#'     \item{s12, s12.2, s12.error, s13, s14}{The stratification variables.}
#'   }
#'
#' @source The data is generated by Yuhan.
#'
#' @keywords dataset
"example"

#' Treatment Assignment Probability Data
#'
#' This dataset gives the assignment probabilities in the example dataset.
#'
#' @format A data frame with 500 rows and 4 columns:
#'   \describe{
#'     \item{1, 2, 3, 4}{The assgiment probabilities of trt 1, 2, 3, and 4.}
#'   }
#'
#' @source The data is generated by Yuhan.
#'
#' @keywords dataset
"prob_mat"

